Hero.create( name: "Mr. Nice" )
Hero.create( name: "Narco" )
Hero.create( name: "Bombasto" )
Hero.create( name: "Celeritas" )
Hero.create( name: "Magneta" )
Hero.create( name: "RubberMan" )
Hero.create( name: "Dynama" )
Hero.create( name: "Dr IQ" )
Hero.create( name: "Magma" )
Hero.create( name: "Tornado" )